### ISSUE TITLE
Duplicate recipe

### ISSUE THREAD

**Issue by isuruf** [conda-forge/pygmo-feedstock#6]
@bluescarni, there was a pygmo recipe here and I completely missed it when reviewing the recipe at staged-recipes. That's why this commit is here, https://github.com/conda-forge/pygmo-feedstock/commit/c3fc55905732fbc84d40f0e33da3e468c9c8ffe0
@xantares, @ccordoba12 sorry about that.

@bluescarni, can you send your recipe to this git repo?

**Comment by bluescarni** [comment]
Ah damn, I missed this as well. I looked only for ``pagmo`` when I was browsing through the conda-forge packages list, and I did not find any pagmo package I just assumed that the pygmo package was not there as well. Apologies.

The situation is a bit complicated by the fact that my recipes refers to pagmo/pygmo version 2.0, which is the new upcoming version and a total rewrite of pagmo/pygmo 1.x. We also have a different repository for it:

https://github.com/esa/pagmo2

vs

https://github.com/esa/pagmo

pagmo/pygmo 1.x and 2.x are essentially different projects, without any binary/source compatibility. They (will) offer more or less the same feature set, but someone who wants to upgrade will have to rewrite all his/her code that uses pagmo.

Any suggestion on how to proceed? Should we split the recipes in different projects (``pagmo`` vs ``pagmo2``)? can we keep on conda-forge older versions of pagmo around?

pinging @darioizzo as well.

**Comment by isuruf** [comment]
There are several options.

1. Use two projects `pagmo` and `pagmo2`
2. Use two different branches on this repo. `master` will point to `pagmo2` and have a new branch `pagmo1.x` to keep maintaining `pagmo 1.x`
3. If `pagmo` is not being maintained, overwrite this recipe and have only `pagmo2`. This doesn't mean the old conda packages will be removed. (they will be kept for users to download.

**Comment by bluescarni** [comment]
``pagmo`` is effectively not maintained any more. So, in order to go with option 3, how would I proceed? I imagine I need to be added to the maintainers of this repo and then I should just copy over the content of the ``recipe`` directory from the PR?

thanks a lot for the help.

**Comment by isuruf** [comment]
You can send a PR and add your username to the maintainers. If @ccordoba12 or @xantares merges the PR you will be given access.

**Comment by isuruf** [comment]
You can also send your changes in the same PR

**Comment by ccordoba12** [comment]
> Use two different branches on this repo. master will point to pagmo2 and have a new branch pagmo1.x to keep maintaining pagmo 1.x

I like this option. Maybe someone still needs Pagmo 1.x, and since there are already recipes for it, we should keep them archived here.

**Comment by bluescarni** [comment]
@ccordoba12 good point. I can work on this in a few hours (this evening, European time).

Should I just modify the contents of the ``recipe`` subdir in the PR? pygmo 2.0 builds also on windows, but I noticed in this feedstock the appveyor build is disabled. How would I re-enable that?

Thanks for the help!

**Comment by isuruf** [comment]
To re-enable that, do `conda smithy rerender`

**Comment by ccordoba12** [comment]
> Should I just modify the contents of the recipe subdir in the PR?

You need to create two PRs:

1. One that creates a new branch for Pagmo 1.x (`pagmo1` seems a good name to me). You need to move the current recipe there. Also, please add to all your commits the message `[ci skip]` to avoid triggering the CIs.
2. A second one with the recipe for Pagmo 2. This PR needs to be done against master.

**Comment by ccordoba12** [comment]
@bluescarni, sorry, you don't need to do **1.** now. I created the `pagmo1` branch myself. Just go for **2.**

**Comment by ccordoba12** [comment]
Closing, as this was solved by #7.
